version: '3'

silent: true

includes:
  devtools:
    taskfile: .taskfile/devtools.yml
  version:
    taskfile: .taskfile/version.yml
  python:
    taskfile: .taskfile/python.yml
  utils:
    taskfile: .taskfile/utils.yml
